services:
  postgres:
    image: postgres:15
    container_name: project-management-db
    environment:
      POSTGRES_DB: projectmanagerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - project-network

  adminer:
    image: adminer:latest
    container_name: project-management-adminer
    ports:
      - "8084:8080"
    depends_on:
      - postgres
    networks:
      - project-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: project-management-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"
    depends_on:
      - postgres
    networks:
      - project-network

  app:
    build: .
    container_name: project-management-app
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/projectmanagerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - project-network
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:

networks:
  project-network:
    driver: bridge 